name: youthetree
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^0.5.27+3
  location: ^3.0.2
  geolocator: ^5.3.1
  permission_handler: ^5.0.0+hotfix.5
  fluttertoast: ^4.0.1
  flutter_polyline_points: ^0.2.1
  intro_slider: ^2.2.9

  provider: ^4.0.5+1
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  rxdart: ^0.23.1
  image_picker: ^0.6.6+1
  geoflutterfire: ^2.1.0
  simple_logger: ^1.7.0


dev_dependencies:
  build_runner: ^1.2.7

flutter:
  uses-material-design: true

